version: '3.8'

services:
  prueba_angular_frontend:
    build: .
    container_name: prueba_angular_frontend
    ports:
      - '4200:4200'
      - '4300:4300'
    volumes:
      - ./app/frontend:/app
    working_dir: /app
    restart: unless-stopped
    networks:
      - db_net
    stdin_open: true
    tty: true
    command: tail -f /dev/null
networks:
  db_net:
    external: true
